name: CI

on:
  push:
    branches: [ "pipelines" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo Hello, world!     
  test1:
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test2:
    needs: [test1]
    runs-on: self-hosted
    steps:
      - name: Check runner info
        run: |
          echo "Running on: $(hostname)"
          echo "OS: $(uname -a)"
          echo "Current directory: $(pwd)"
          echo "Docker version: $(docker --version)"

